---
name: backend-database
services:
  database:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataweb
    volumes:
      - "database-data:/var/lib/postgresql/data"
  backend:
    build: .
    container_name: proxecto-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env.dev

volumes:
  database-data: