---
name: backend-database
services:
  database:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    environment:
      # Default password intended for local development used only!
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataWeb
    volumes:
      - "database-data:/var/lib/postgresql/data"
  backend:
    build: .
    container_name: proxecto-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DB_NAME: proxectodb
      DB_USER: usuario
      DB_PASSWORD: contrasinal
      DB_HOST: db
      DB_PORT: 5432

volumes:
  database-data: