# Generated by Django 5.2.7 on 2025-11-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bknd_talleres', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taller',
            new_name='TallerService',
        ),
    ]
