# Generated by Django 5.2.7 on 2025-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bknd_talleres', '0002_rename_taller_tallerservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallerservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='talleres/'),
        ),
    ]
