# Generated by Django 5.2.7 on 2025-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bknd_talleres', '0003_alter_tallerservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tallerservice',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
